saar_formulario:
    resource: "@SaarBundle/Controller/FormularioController.php"
    type:     annotation

saar_empresa:
    resource: "@SaarBundle/Controller/EmpresaController.php"
    type:     annotation
    prefix:   /empresa


user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

saar:
    resource: "@SaarBundle/Controller/"
    type:     annotation
    prefix:   /saar

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
