user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

saar:
    resource: "@SaarBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
